binarytea:
  ready: true
  open-hours: 8:30-22:00

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,shop,metrics

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        show_sql: true # 与下面语句效果等同
    show-sql: true