binarytea:
  ready: true
  open-hours: 8:30-22:00

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,shop,metrics
mybatis:
  type-handlers-package: learning.spring.binarytea.support.handler
  type-aliases-package: learning.spring.binarytea.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml

pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true
